// Generated by scripts/registry-schemas.ts. Do not edit.
export const schemas = {
  "stat-tile": {
    "type": "object",
    "properties": {
      "LABEL": {
        "type": "string",
        "default": ""
      },
      "VALUE": {
        "type": "number",
        "default": 0
      }
    },
    "required": [
      "LABEL",
      "VALUE"
    ],
    "additionalProperties": false
  },
  "list-tile": {
    "type": "object",
    "properties": {
      "LIST_TITLE": {
        "type": "string",
        "default": ""
      },
      "LIST_ITEMS": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "LIST_TITLE",
      "LIST_ITEMS"
    ],
    "additionalProperties": false
  },
  "checklist-tile": {
    "type": "object",
    "properties": {
      "CHECKLIST_TITLE": {
        "type": "string",
        "default": ""
      },
      "CHECKLIST_ITEMS": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "LABEL": {
              "type": "string",
              "default": ""
            },
            "CHECKED": {
              "type": "boolean",
              "default": false
            }
          },
          "required": [
            "LABEL",
            "CHECKED"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "CHECKLIST_TITLE",
      "CHECKLIST_ITEMS"
    ],
    "additionalProperties": false
  },
  "eisenhower-matrix-tile": {
    "type": "object",
    "properties": {
      "MATRIX_TITLE": {
        "type": "string",
        "default": ""
      },
      "MATRIX_ITEMS": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "task": {
              "type": "string",
              "default": ""
            },
            "urgency": {
              "type": "string",
              "enum": [
                "High",
                "Low"
              ]
            },
            "importance": {
              "type": "string",
              "enum": [
                "High",
                "Low"
              ]
            }
          },
          "required": [
            "task",
            "urgency",
            "importance"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "MATRIX_TITLE",
      "MATRIX_ITEMS"
    ],
    "additionalProperties": false
  }
} as const
