// Generated by scripts/registry-schemas.ts. Do not edit.
export const schemas = {
  "stat-tile": {
    type: "object",
    properties: {
      LABEL: {
        type: "string",
        default: "",
      },
      VALUE: {
        type: "number",
        default: 0,
      },
    },
    required: ["LABEL", "VALUE"],
    additionalProperties: false,
  },
  "list-tile": {
    type: "object",
    properties: {
      LIST_TITLE: {
        type: "string",
        default: "",
      },
      LIST_ITEMS: {
        type: "array",
        items: {
          type: "string",
        },
      },
    },
    required: ["LIST_TITLE", "LIST_ITEMS"],
    additionalProperties: false,
  },
} as const;
