import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"

type RegistryItem = { readonly name: string; readonly meta?: { readonly schema?: unknown } }
type Registry = { readonly items: readonly RegistryItem[] }

const root = path.resolve(import.meta.dirname, "..")
const registry = JSON.parse(readFileSync(path.join(root, "registry.json"), "utf8")) as Registry

const entries = registry.items.map((item) => [item.name, item.meta?.schema ?? {}] as const)

const output = `// Generated by scripts/registry-schemas.ts. Do not edit.
export const schemas = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const
`

writeFileSync(path.join(root, "src/registry/schemas.generated.ts"), output, "utf8")
