import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Registry = {
  readonly items: readonly {
    readonly name: string;
    readonly meta?: { readonly schema?: unknown };
  }[];
};

export function generateSchemas(root: string): void {
  const registry = JSON.parse(
    readFileSync(path.join(root, "registry.json"), "utf8"),
  ) as Registry;
  const entries = registry.items.map(
    (item) => [item.name, item.meta?.schema ?? {}] as const,
  );
  const output = `// Generated by scripts/registry-schemas.ts. Do not edit.\nexport const schemas = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const\n`;
  writeFileSync(path.join(root, "registry/schemas.generated.ts"), output, "utf8");
}
